//
//  QRCodeViewController.h
//  Business Card
//
//  After user created his/her own profile, a user can share the profile using a qr code by choosing the QR Code button in the namecard view.
//  The QR Code is generated by Google API with the id number and name.
//
//  Created by Kar Mun Pui on 11/06/14.
//  Copyright (c) 2014 Kar Mun Pui. All rights reserved.
//

#import <UIKit/UIKit.h>

@interface QRCodeViewController : UIViewController

@property (weak, nonatomic) IBOutlet UIImageView *QRImageView;
@property (nonatomic, strong) UIImage *image;

@property (nonatomic, retain) NSString * url;

@end
